name: CI

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  test:
    name: Lint, TypeCheck & Test
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Generate Prisma Client
        run: npm run db:generate

      - name: Run ESLint
        run: npm run lint

      - name: Run TypeScript Check
        run: npm run typecheck

      - name: Run Tests (Pinned Prisma CLI)
        env:
          DATABASE_URL: "file:${{ github.workspace }}/prisma/test.db"
        run: |
          # Prepare DB with Prisma v6 regardless of workspace deps
          npx prisma@6.15.0 db push --schema prisma/schema.prisma --force-reset
          # Run backend tests from backend directory so dotenv paths resolve
          cd backend
          export DATABASE_URL="file:${GITHUB_WORKSPACE}/prisma/test.db"
          npx jest
          # Run frontend tests as usual
          cd ..
          npm run test:frontend

  # Optional: Auto-format and commit (uncomment to enable)
  # format:
  #   name: Auto-format Code
  #   runs-on: ubuntu-latest
  #   if: github.event_name == 'pull_request'
  #   
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4
  #       with:
  #         token: ${{ secrets.GITHUB_TOKEN }}
  #         ref: ${{ github.head_ref }}

  #     - name: Setup Node.js
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: '20.x'
  #         cache: 'npm'

  #     - name: Install dependencies
  #       run: npm ci

  #     - name: Format code
  #       run: |
  #         cd frontend && npm run lint -- --fix
  #         cd ../backend && npm run lint -- --fix

  #     - name: Commit changes
  #       run: |
  #         git config --local user.email "action@github.com"
  #         git config --local user.name "GitHub Action"
  #         git add -A
  #         git diff --cached --quiet || git commit -m "style: auto-format code"
  #         git push
