name: CI

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  test:
    name: Lint, TypeCheck & Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        bun-version: [latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Generate Prisma Client
        run: bun run db:generate

      - name: Run ESLint
        run: bun run lint

      - name: Run TypeScript Check
        run: bun run typecheck

      - name: Run Tests
        env:
          DATABASE_URL: "file:${{ github.workspace }}/prisma/test.db"
          VITE_API_URL: "http://localhost:3001"
        run: bun run test:bun

  # Optional: Auto-format and commit (uncomment to enable)
  # format:
  #   name: Auto-format Code
  #   runs-on: ubuntu-latest
  #   if: github.event_name == 'pull_request'
  #
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v5
  #       with:
  #         token: ${{ secrets.GITHUB_TOKEN }}
  #         ref: ${{ github.head_ref }}

  #     - name: Setup Bun
  #       uses: oven-sh/setup-bun@v1
  #       with:
  #         bun-version: latest

  #     - name: Install dependencies
  #       run: bun install --frozen-lockfile

  #     - name: Format code
  #       run: |
  #         cd frontend && bun run lint -- --fix
  #         cd ../backend && bun run lint -- --fix

  #     - name: Commit changes
  #       run: |
  #         git config --local user.email "action@github.com"
  #         git config --local user.name "GitHub Action"
  #         git add -A
  #         git diff --cached --quiet || git commit -m "style: auto-format code"
  #         git push
